'use client';

import type { ChecklistItem, ChecklistProgress, RiskTier } from '@eu-ai-act/sdk';
import { countProgress } from '@eu-ai-act/sdk';

/** Tier display labels. */
const TIER_LABELS: Record<RiskTier, string> = {
  prohibited: 'Prohibited',
  'high-risk': 'High-Risk',
  gpai: 'General-Purpose AI (GPAI)',
  'gpai-systemic': 'GPAI with Systemic Risk',
  limited: 'Limited Risk',
  minimal: 'Minimal Risk',
};

/**
 * Format a checklist category string for display.
 * e.g., "risk-management" -> "Risk Management"
 */
function formatCategory(cat: string): string {
  return cat
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/**
 * Export checklist as Markdown.
 */
export function exportChecklistAsMarkdown(
  tier: RiskTier,
  items: ChecklistItem[],
  progress: Record<string, ChecklistProgress>,
  systemName?: string,
  provider?: string,
): string {
  const { completed, total, percent } = countProgress(items, progress);
  const date = new Date().toISOString().split('T')[0];

  const lines: string[] = [];
  lines.push(`# EU AI Act Compliance Checklist — ${TIER_LABELS[tier]}`);
  lines.push('');
  if (systemName) lines.push(`**System**: ${systemName}`);
  if (provider) lines.push(`**Provider**: ${provider}`);
  lines.push(`**Tier**: ${TIER_LABELS[tier]}`);
  lines.push(`**Date**: ${date}`);
  lines.push(`**Progress**: ${completed}/${total} items complete (${percent}%)`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Group by category
  const grouped = new Map<string, ChecklistItem[]>();
  for (const item of items) {
    const existing = grouped.get(item.category) ?? [];
    existing.push(item);
    grouped.set(item.category, existing);
  }

  for (const [category, catItems] of grouped) {
    lines.push(`## ${formatCategory(category)}`);
    lines.push('');
    for (const item of catItems) {
      const checked = progress[item.id]?.checked === true;
      const mark = checked ? 'x' : ' ';
      const required = item.required ? '' : ' *(optional)*';
      lines.push(`- [${mark}] **Art. ${item.article}${item.paragraph ? `(${item.paragraph})` : ''}**: ${item.text}${required}`);

      if (item.description) {
        lines.push(`  > ${item.description}`);
      }

      if (checked && progress[item.id]?.evidence) {
        lines.push(`  - **Evidence**: ${progress[item.id]!.evidence}`);
      }
      if (checked && progress[item.id]?.checkedAt) {
        lines.push(`  - **Completed**: ${progress[item.id]!.checkedAt!.split('T')[0]}`);
      }
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by EU AI Act Compliance Toolkit — https://github.com/AbdelStark/eu-ai-act-toolkit*');
  lines.push('');
  lines.push('*This checklist does not constitute legal advice. Consult qualified legal counsel for compliance decisions.*');

  return lines.join('\n');
}

/**
 * Export checklist as CSV.
 */
export function exportChecklistAsCsv(
  tier: RiskTier,
  items: ChecklistItem[],
  progress: Record<string, ChecklistProgress>,
): string {
  const lines: string[] = [];

  // Header
  lines.push('ID,Article,Paragraph,Category,Text,Description,Required,Completed,Evidence,Completed Date');

  for (const item of items) {
    const prog = progress[item.id];
    const checked = prog?.checked === true;
    const evidence = prog?.evidence ?? '';
    const checkedAt = prog?.checkedAt ?? '';

    // CSV escape: wrap in quotes and double any existing quotes
    const escape = (s: string) => `"${s.replace(/"/g, '""')}"`;

    lines.push([
      escape(item.id),
      item.article.toString(),
      item.paragraph?.toString() ?? '',
      escape(formatCategory(item.category)),
      escape(item.text),
      escape(item.description),
      item.required ? 'Yes' : 'No',
      checked ? 'Yes' : 'No',
      escape(evidence),
      checkedAt ? checkedAt.split('T')[0] ?? '' : '',
    ].join(','));
  }

  return lines.join('\n');
}

/**
 * Download a string as a file.
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
